CREATE TABLE [ERP].[AplicacionAnticipoPagar] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [IdCuentaPagar]     INT             NULL,
    [IdProveedor]       INT             NULL,
    [IdMoneda]          INT             NULL,
    [IdTipoComprobante] INT             NULL,
    [Documento]         VARCHAR (20)    NULL,
    [Serie]             VARCHAR (4)     NULL,
    [Fecha]             DATETIME        NULL,
    [TipoCambio]        DECIMAL (14, 5) NULL,
    [Total]             DECIMAL (14, 5) NULL,
    [FechaRegistro]     DATETIME        NULL,
    [UsuarioRegistro]   VARCHAR (250)   NULL,
    [IdAsiento]         INT             NULL,
    [IdEmpresa]         INT             NULL,
    [Flag]              BIT             NULL,
    [FechaAplicacion]   DATETIME        NULL,
    CONSTRAINT [PK__Aplicaci__3214EC27EF214FA0] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Aplicacio__IdAsi__3E7DF7EB] FOREIGN KEY ([IdAsiento]) REFERENCES [ERP].[Asiento] ([ID]),
    CONSTRAINT [FK__Aplicacio__IdCue__735BD47E] FOREIGN KEY ([IdCuentaPagar]) REFERENCES [ERP].[CuentaPagar] ([ID]),
    CONSTRAINT [FK__Aplicacio__IdMon__75441CF0] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK__Aplicacio__IdPro__744FF8B7] FOREIGN KEY ([IdProveedor]) REFERENCES [ERP].[Proveedor] ([ID]),
    CONSTRAINT [FK__Aplicacio__IdTip__76384129] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID])
);

