CREATE TABLE [ERP].[Compra] (
    [ID]                            INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]                     INT             NULL,
    [IdPeriodo]                     INT             NULL,
    [Orden]                         INT             NULL,
    [IdProveedor]                   INT             NULL,
    [FechaEmision]                  DATETIME        NULL,
    [IdMoneda]                      INT             NULL,
    [IdTipoComprobante]             INT             NULL,
    [Serie]                         CHAR (4)        NULL,
    [Numero]                        VARCHAR (20)    NULL,
    [TipoCambio]                    DECIMAL (14, 5) NULL,
    [PorcentajeIGV]                 DECIMAL (14, 5) NULL,
    [IdTipoIGV]                     INT             NULL,
    [FechaVencimiento]              DATETIME        NULL,
    [BaseImponible]                 DECIMAL (14, 5) NULL,
    [Inafecto]                      DECIMAL (14, 5) NULL,
    [IGV]                           DECIMAL (14, 5) NULL,
    [ISC]                           DECIMAL (14, 5) NULL,
    [OtroImpuesto]                  DECIMAL (14, 5) NULL,
    [Descuento]                     DECIMAL (14, 5) NULL,
    [RedondeoSuma]                  DECIMAL (14, 5) NULL,
    [RedondeoResta]                 DECIMAL (14, 5) NULL,
    [Total]                         DECIMAL (14, 5) NULL,
    [FechaModificado]               DATETIME        NULL,
    [UsuarioRegistro]               VARCHAR (250)   NULL,
    [UsuarioModifico]               VARCHAR (250)   NULL,
    [UsuarioElimino]                VARCHAR (250)   NULL,
    [UsuarioActivo]                 VARCHAR (250)   NULL,
    [FechaActivacion]               DATETIME        NULL,
    [FechaRecepcion]                DATETIME        NULL,
    [FlagBorrador]                  BIT             NULL,
    [IdDetraccion]                  INT             NULL,
    [Flag]                          BIT             NULL,
    [FechaRegistro]                 DATETIME        NULL,
    [FechaEliminado]                DATETIME        NULL,
    [IdAsiento]                     INT             NULL,
    [Descripcion]                   VARCHAR (MAX)   NULL,
    [ImpuestoRenta]                 DECIMAL (14, 5) NULL,
    [DiasVencimiento]               INT             NULL,
    [ImpuestoRentaSegundaCategoria] DECIMAL (14, 5) NULL,
    [FlagImpuestoSegundaCategoria]  BIT             NULL,
    [PorcentajeDetraccion]          DECIMAL (14, 5) NULL,
    CONSTRAINT [PK_Compra] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Compra__IdAsient__67FF306B] FOREIGN KEY ([IdAsiento]) REFERENCES [ERP].[Asiento] ([ID]),
    CONSTRAINT [FK_Compra_Empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK_Compra_Moneda] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK_Compra_Proveedor] FOREIGN KEY ([IdProveedor]) REFERENCES [ERP].[Proveedor] ([ID]),
    CONSTRAINT [FK_Compra_T10TipoComprobante] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID]),
    CONSTRAINT [FK_Compra_TipoIGV] FOREIGN KEY ([IdTipoIGV]) REFERENCES [Maestro].[TipoIGV] ([ID])
);

