CREATE TABLE [ERP].[Comprobante] (
    [ID]                             INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]                      INT             NOT NULL,
    [IdTipoComprobante]              INT             NOT NULL,
    [IdCliente]                      INT             NULL,
    [IdProyecto]                     INT             NULL,
    [IdVendedor]                     INT             NULL,
    [IdAlmacen]                      INT             NULL,
    [IdUsuario]                      INT             NULL,
    [IdMoneda]                       INT             NULL,
    [IdListaPrecio]                  INT             NULL,
    [IdComprobanteEstado]            INT             NULL,
    [IdAsiento]                      INT             NULL,
    [IdMotivoNotaCredito]            INT             NULL,
    [Serie]                          CHAR (4)        NULL,
    [Documento]                      VARCHAR (20)    NULL,
    [SerieDocumentoComprobante]      VARCHAR (20)    NULL,
    [SerieDocumentoComprobanteSunat] VARCHAR (20)    NULL,
    [Fecha]                          DATETIME        NULL,
    [TipoCambio]                     DECIMAL (14, 5) NULL,
    [PorcentajeIGV]                  DECIMAL (14, 5) NULL,
    [PorcentajeDescuento]            DECIMAL (14, 5) NULL,
    [TotalDetalleISC]                DECIMAL (14, 5) NULL,
    [TotalDetalleAfecto]             DECIMAL (14, 5) NULL,
    [TotalDetalleInafecto]           DECIMAL (14, 5) NULL,
    [TotalDetalleExportacion]        DECIMAL (14, 5) NULL,
    [TotalDetalleGratuito]           DECIMAL (14, 5) NULL,
    [TotalDetalle]                   DECIMAL (14, 5) NULL,
    [ImporteDescuento]               DECIMAL (14, 5) NULL,
    [SubTotal]                       DECIMAL (14, 5) NULL,
    [IGV]                            DECIMAL (14, 5) NULL,
    [Total]                          DECIMAL (14, 5) NULL,
    [ISC]                            DECIMAL (14, 5) NULL,
    [ImportePercepcion]              DECIMAL (14, 5) NULL,
    [TotalPercepcion]                DECIMAL (14, 5) NULL,
    [FechaRegistro]                  DATETIME        NULL,
    [FechaEliminado]                 DATETIME        NULL,
    [FlagBorrador]                   BIT             NULL,
    [Flag]                           BIT             NULL,
    [FlagExportacion]                BIT             NULL,
    [RutaDocumentoXML]               VARCHAR (250)   NULL,
    [RutaDocumentoPDF]               VARCHAR (250)   NULL,
    [Observacion]                    VARCHAR (250)   NULL,
    [IdMotivoNotaDebito]             INT             NULL,
    [FechaModificado]                DATETIME        NULL,
    [UsuarioRegistro]                VARCHAR (250)   NULL,
    [UsuarioModifico]                VARCHAR (250)   NULL,
    [FlagPercepcion]                 BIT             NULL,
    [PorcentajePercepcion]           DECIMAL (14, 5) NULL,
    [PorcentajeDetraccion]           DECIMAL (14, 5) NULL,
    [ImporteDetraccion]              DECIMAL (14, 5) NULL,
    [TotalDetraccion]                DECIMAL (14, 5) NULL,
    [FlagDetraccion]                 BIT             NULL,
    [FlagAnticipo]                   BIT             NULL,
    [IdDetraccion]                   INT             NULL,
    [FlagResumenDiario]              BIT             NULL,
    [IdCuentaCobrar]                 INT             NULL,
    [CodigoHash]                     VARCHAR (MAX)   NULL,
    [SignatureValue]                 VARCHAR (MAX)   NULL,
    [FlagComprobanteElectronico]     BIT             NULL,
    [NumeroPlaca]                    VARCHAR (10)    NULL,
    [RutaDocumentoCDR]               VARCHAR (MAX)   NULL,
    [FlagGrifo]                      BIT             NULL,
    [IdEstablecimiento]              INT             NULL,
    [FechaVencimiento]               DATETIME        NULL,
    [DiasVencimiento]                INT             NULL,
    [CorrelativoAnulacionSunat]      INT             NULL,
    [FechaAnulado]                   DATETIME        NULL,
    [UsuarioAnulo]                   VARCHAR (250)   NULL,
    [TicketAnulacion]                VARCHAR (250)   NULL,
    [IdVale]                         INT             NULL,
    [FlagControlarStock]             BIT             NULL,
    [FlagGenerarVale]                BIT             NULL,
    [MensajeSunat]                   VARCHAR (MAX)   NULL,
    [IdCuentaDetraccion]             INT             NULL,
    [CondicionPago]                  VARCHAR (255)   NULL,
    [IdEstablecimientoCliente]       INT             NULL,
    [PorcentajeAdelanto]             DECIMAL (14, 5) NULL,
    [ImporteAdelanto]                DECIMAL (14, 5) NULL,
    [IdEfectivo]                     INT             NULL,
    CONSTRAINT [PK__Comproba__3214EC2780DDFAEF] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Comproban__IdCli__515009E6] FOREIGN KEY ([IdCliente]) REFERENCES [ERP].[Cliente] ([ID]),
    CONSTRAINT [FK__Comproban__IdEmp__4F67C174] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK__Comproban__IdLis__5614BF03] FOREIGN KEY ([IdListaPrecio]) REFERENCES [ERP].[ListaPrecio] ([ID]),
    CONSTRAINT [FK__Comproban__IdMon__55209ACA] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK__Comproban__IdPro__52442E1F] FOREIGN KEY ([IdProyecto]) REFERENCES [ERP].[Proyecto] ([ID]),
    CONSTRAINT [FK__Comproban__IdTip__505BE5AD] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID]),
    CONSTRAINT [FK__Comproban__IdVen__53385258] FOREIGN KEY ([IdVendedor]) REFERENCES [ERP].[Vendedor] ([ID]),
    CONSTRAINT [FK_Comprobante_Almacen] FOREIGN KEY ([IdAlmacen]) REFERENCES [ERP].[Almacen] ([ID]),
    CONSTRAINT [FK_Comprobante_Asiento] FOREIGN KEY ([IdAsiento]) REFERENCES [ERP].[Asiento] ([ID]),
    CONSTRAINT [FK_Comprobante_ComprobanteEstado] FOREIGN KEY ([IdComprobanteEstado]) REFERENCES [Maestro].[ComprobanteEstado] ([ID]),
    CONSTRAINT [FK_Comprobante_Detraccion] FOREIGN KEY ([IdDetraccion]) REFERENCES [Maestro].[Detraccion] ([ID]),
    CONSTRAINT [FK_Comprobante_MotivoNotaCredito] FOREIGN KEY ([IdMotivoNotaCredito]) REFERENCES [XML].[T9MotivoNotaCredito] ([ID]),
    CONSTRAINT [FK_Comprobante_MotivoNotaDebito] FOREIGN KEY ([IdMotivoNotaDebito]) REFERENCES [XML].[T10MotivoNotaDebito] ([ID]),
    CONSTRAINT [fk_Comprobante_Usuario] FOREIGN KEY ([IdUsuario]) REFERENCES [Seguridad].[Usuario] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ID]
    ON [ERP].[Comprobante]([ID] ASC);

