CREATE TABLE [ERP].[CuentaPagar] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]           INT             NOT NULL,
    [IdEntidad]           INT             NOT NULL,
    [Fecha]               DATETIME        NULL,
    [IdTipoComprobante]   INT             NULL,
    [Serie]               VARCHAR (4)     NULL,
    [Numero]              VARCHAR (20)    NULL,
    [Total]               DECIMAL (14, 5) NULL,
    [TipoCambio]          DECIMAL (14, 5) NULL,
    [IdMoneda]            INT             NULL,
    [IdCuentaPagarOrigen] INT             NULL,
    [Flag]                BIT             NULL,
    [FlagCancelo]         BIT             NULL,
    [FlagDetraccion]      BIT             NULL,
    [FechaVencimiento]    DATETIME        NULL,
    [IdDebeHaber]         INT             NULL,
    [FlagAnticipo]        BIT             NULL,
    [FechaRecepcion]      DATETIME        NULL,
    [IdPeriodo]           INT             NULL,
    [FlagImpuestoRenta]   BIT             NULL,
    CONSTRAINT [PK__CuentaPa__3214EC2794EB5BEF] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__CuentaPag__IdCue__0E04DDC2] FOREIGN KEY ([IdCuentaPagarOrigen]) REFERENCES [Maestro].[CuentaPagarOrigen] ([ID]),
    CONSTRAINT [FK__CuentaPag__IdDeb__44A0E595] FOREIGN KEY ([IdDebeHaber]) REFERENCES [Maestro].[DebeHaber] ([ID]),
    CONSTRAINT [FK__CuentaPag__IdEmp__0A344CDE] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK__CuentaPag__IdEnt__0B287117] FOREIGN KEY ([IdEntidad]) REFERENCES [ERP].[Entidad] ([ID]),
    CONSTRAINT [FK__CuentaPag__IdMon__0D10B989] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK__CuentaPag__IdTip__0C1C9550] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID])
);

