CREATE TABLE [ERP].[Cuenta] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [IdEntidad]           INT             NULL,
    [Nombre]              VARCHAR (50)    NULL,
    [IdMoneda]            INT             NULL,
    [IdTipoCuenta]        INT             NULL,
    [IdPlanCuenta]        INT             NULL,
    [Fecha]               DATETIME        NULL,
    [SaldoInicialDebe]    DECIMAL (16, 5) NULL,
    [SaldoInicialHaber]   DECIMAL (16, 5) NULL,
    [FechaRegistro]       DATETIME        NULL,
    [FechaEliminado]      DATETIME        NULL,
    [FlagBorrador]        BIT             NULL,
    [Flag]                BIT             NULL,
    [IdEmpresa]           INT             NULL,
    [FechaModificado]     DATETIME        NULL,
    [UsuarioRegistro]     VARCHAR (250)   NULL,
    [UsuarioModifico]     VARCHAR (250)   NULL,
    [UsuarioElimino]      VARCHAR (250)   NULL,
    [UsuarioActivo]       VARCHAR (250)   NULL,
    [FechaActivacion]     DATETIME        NULL,
    [CuentaInterbancario] VARCHAR (20)    NULL,
    [FlagDetraccion]      BIT             NULL,
    [FlagContabilidad]    BIT             NULL,
    [MostrarEnFE]         BIT             NULL,
    CONSTRAINT [PK_Cuenta] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Cuenta_Entidad] FOREIGN KEY ([IdEntidad]) REFERENCES [ERP].[Entidad] ([ID]),
    CONSTRAINT [FK_Cuenta_Moneda] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK_Cuenta_PlanCuenta] FOREIGN KEY ([IdPlanCuenta]) REFERENCES [ERP].[PlanCuenta] ([ID]),
    CONSTRAINT [FK_Cuenta_TipoCuenta] FOREIGN KEY ([IdTipoCuenta]) REFERENCES [Maestro].[TipoCuenta] ([ID])
);

