CREATE TABLE [ERP].[DatoLaboralDetalle] (
    [ID]                                INT             IDENTITY (1, 1) NOT NULL,
    [IdDatoLaboral]                     INT             NULL,
    [IdRegimenLaboral]                  INT             NULL,
    [IdTipoTrabajador]                  INT             NULL,
    [IdPuesto]                          INT             NULL,
    [IdTipoSueldo]                      INT             NULL,
    [Sueldo]                            DECIMAL (14, 5) NULL,
    [FechaInicio]                       DATETIME        NULL,
    [FechaFin]                          DATETIME        NULL,
    [IdCategoriaDatoLaboral]            INT             NULL,
    [IdPlanilla]                        INT             NULL,
    [IdCategoriaOcupacional]            INT             NULL,
    [FlagJornadaTrabajoMaxima]          BIT             NULL,
    [FlagJornadaAtipica]                BIT             NULL,
    [FlagJornadaTrabajoHorarioNocturno] BIT             NULL,
    [IdSituacionEspecialTrabajador]     INT             NULL,
    [FlagSindicalizado]                 BIT             NULL,
    [IdSituacionTrabajador]             INT             NULL,
    [FlagPersonaDiscapacidad]           BIT             NULL,
    [UsuarioRegistro]                   VARCHAR (250)   NULL,
    [FechaRegistro]                     DATETIME        NULL,
    [UsuarioModifico]                   VARCHAR (250)   NULL,
    [FechaModifico]                     DATETIME        NULL,
    [HoraBase]                          DECIMAL (14, 5) NULL,
    [IdEstadoTrabajador]                INT             NULL,
    CONSTRAINT [PK__DatoLabo__3214EC27E18657FE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__DatoLabor__IdCat__458BB384] FOREIGN KEY ([IdCategoriaDatoLaboral]) REFERENCES [Maestro].[CategoriaDatoLaboral] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdCat__495C4468] FOREIGN KEY ([IdCategoriaOcupacional]) REFERENCES [PLAME].[T24CategoriaOcupacional] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdDat__14DD8F31] FOREIGN KEY ([IdDatoLaboral]) REFERENCES [ERP].[DatoLaboral] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdPla__51F18A69] FOREIGN KEY ([IdPlanilla]) REFERENCES [Maestro].[Planilla] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdPue__79206623] FOREIGN KEY ([IdPuesto]) REFERENCES [Maestro].[Puesto] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdReg__0DE678DF] FOREIGN KEY ([IdRegimenLaboral]) REFERENCES [PLAME].[T33RegimenLaboral] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdSit__4A5068A1] FOREIGN KEY ([IdSituacionEspecialTrabajador]) REFERENCES [PLAME].[T35SituacionEspecialTrabajador] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdSit__4B448CDA] FOREIGN KEY ([IdSituacionTrabajador]) REFERENCES [PLAME].[T15SituacionTrabajador] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdTip__15D1B36A] FOREIGN KEY ([IdTipoTrabajador]) REFERENCES [PLAME].[T8TipoTrabajador] ([ID]),
    CONSTRAINT [FK__DatoLabor__IdTip__63F03F13] FOREIGN KEY ([IdTipoSueldo]) REFERENCES [Maestro].[TipoSueldo] ([ID])
);

