CREATE TABLE [ERP].[Establecimiento] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [IdEntidad]             INT           NULL,
    [Nombre]                VARCHAR (250) NULL,
    [Direccion]             VARCHAR (250) NULL,
    [IdTipoEstablecimiento] INT           NULL,
    [IdVia]                 INT           NULL,
    [ViaNombre]             VARCHAR (250) NULL,
    [ViaNumero]             VARCHAR (4)   NULL,
    [Interior]              VARCHAR (4)   NULL,
    [IdZona]                INT           NULL,
    [ZonaNombre]            VARCHAR (250) NULL,
    [Referencia]            VARCHAR (250) NULL,
    [IdUbigeo]              INT           NULL,
    [Sector]                VARCHAR (20)  NULL,
    [Grupo]                 VARCHAR (20)  NULL,
    [Manzana]               VARCHAR (20)  NULL,
    [Lote]                  VARCHAR (20)  NULL,
    [Kilometro]             VARCHAR (20)  NULL,
    [IdPais]                INT           NULL,
    [Telefono]              VARCHAR (50)  NULL,
    [Celular]               VARCHAR (50)  NULL,
    [UsuarioRegistro]       VARCHAR (250) NULL,
    [FechaRegistro]         DATETIME      NULL,
    [UsuarioModifico]       VARCHAR (250) NULL,
    [FechaModificado]       DATETIME      NULL,
    [UsuarioElimino]        VARCHAR (250) NULL,
    [FechaEliminado]        DATETIME      NULL,
    [UsuarioActivo]         VARCHAR (250) NULL,
    [FechaActivacion]       DATETIME      NULL,
    [FlagSistema]           BIT           NULL,
    [FlagBorrador]          BIT           NULL,
    [Flag]                  BIT           NULL,
    CONSTRAINT [PK__Establec__3214EC27EAA18AE5] PRIMARY KEY CLUSTERED ([ID] ASC)
);

