CREATE TABLE [ERP].[KardexRecalculo] (
    [ROWid]                  INT             NOT NULL,
    [IDmaestro]              INT             NULL,
    [Fecha]                  DATETIME        NULL,
    [IdTipoMovimiento]       INT             NULL,
    [FlagCostear]            INT             NULL,
    [IDdetalle]              INT             NULL,
    [IdProducto]             INT             NULL,
    [Nombre]                 VARCHAR (250)   NULL,
    [Cantidad]               DECIMAL (20, 8) NULL,
    [SubTotal]               DECIMAL (20, 8) NULL,
    [PrecioUnitario]         DECIMAL (20, 8) NULL,
    [IdMoneda]               INT             NULL,
    [TipoCambio]             DECIMAL (20, 8) NULL,
    [CalculadoPU]            DECIMAL (20, 8) NULL,
    [CalculadoPP]            DECIMAL (20, 8) NULL,
    [AcumuladoCant]          DECIMAL (20, 8) NULL,
    [AcumuladoSaldo]         DECIMAL (20, 8) NULL,
    [IdConcepto]             INT             NULL,
    [IdAlmacen]              INT             NULL,
    [IdProyecto]             INT             NULL,
    [FlagTraEntreAlm]        INT             NULL,
    [Documento]              VARCHAR (50)    NULL,
    [SubtotalCalculado]      DECIMAL (20, 8) NULL,
    [TotalCalculado]         DECIMAL (20, 8) NULL,
    [IgvCalculado]           DECIMAL (20, 8) NULL,
    [PrecioMonedaOriginal]   DECIMAL (20, 8) NULL,
    [TotalMonedaOriginal]    DECIMAL (20, 8) NULL,
    [SubtotalMonedaOriginal] DECIMAL (20, 8) NULL,
    [IGVmonedaOriginal]      DECIMAL (20, 8) NULL,
    [TotalMbase]             DECIMAL (20, 8) NULL,
    [SubtotalMbase]          DECIMAL (20, 8) NULL,
    [IGVMbase]               DECIMAL (20, 8) NULL,
    CONSTRAINT [PK_KardexRecalculo] PRIMARY KEY CLUSTERED ([ROWid] ASC)
);

