CREATE TABLE [ERP].[MovimientoTransferenciaCuenta] (
    [ID]                                INT             IDENTITY (1, 1) NOT NULL,
    [IdCuentaEmisor]                    INT             NULL,
    [IdCategoriaTipoMovimientoEmisor]   INT             NULL,
    [FechaEmisor]                       DATETIME        NULL,
    [FechaVencimientoEmisor]            DATETIME        NULL,
    [TipoCambioEmisor]                  DECIMAL (14, 5) NULL,
    [MontoEmisor]                       DECIMAL (14, 5) NULL,
    [OrdenDeEmisor]                     VARCHAR (250)   NULL,
    [AjusteEmisor]                      DECIMAL (14, 5) NULL,
    [ConceptoEmisor]                    VARCHAR (250)   NULL,
    [ObservacionEmisor]                 VARCHAR (250)   NULL,
    [IdCuentaReceptor]                  INT             NULL,
    [IdCategoriaTipoMovimientoReceptor] INT             NULL,
    [FechaReceptor]                     DATETIME        NULL,
    [DocumentoReceptor]                 VARCHAR (25)    NULL,
    [TipoCambioReceptor]                DECIMAL (14, 5) NULL,
    [MontoReceptor]                     DECIMAL (14, 5) NULL,
    [ConceptoReceptor]                  VARCHAR (250)   NULL,
    [ObservacionReceptor]               VARCHAR (250)   NULL,
    [IdEmpresa]                         INT             NULL,
    [IdMovimientoTesoreriaEmisor]       INT             NULL,
    [IdMovimientoTesoreriaReceptor]     INT             NULL,
    [FlagBorrador]                      INT             NULL,
    [Flag]                              INT             NULL,
    [IdTalonarioEmisor]                 INT             NULL,
    [NumeroChequeEmisor]                INT             NULL,
    [FlagCajaChica]                     BIT             NULL,
    [FlagCheque]                        BIT             NULL,
    [FlagChequeDiferido]                BIT             NULL,
    [DocumentoEmisor]                   VARCHAR (25)    NULL,
    CONSTRAINT [PK__Movimien__3214EC277153058B] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Movimient__IdCat__6CC3E588] FOREIGN KEY ([IdCategoriaTipoMovimientoEmisor]) REFERENCES [Maestro].[CategoriaTipoMovimiento] ([ID]),
    CONSTRAINT [FK__Movimient__IdCat__6DB809C1] FOREIGN KEY ([IdCategoriaTipoMovimientoReceptor]) REFERENCES [Maestro].[CategoriaTipoMovimiento] ([ID]),
    CONSTRAINT [FK__Movimient__IdCue__6EAC2DFA] FOREIGN KEY ([IdCuentaEmisor]) REFERENCES [ERP].[Cuenta] ([ID]),
    CONSTRAINT [FK__Movimient__IdCue__6FA05233] FOREIGN KEY ([IdCuentaReceptor]) REFERENCES [ERP].[Cuenta] ([ID])
);

