CREATE TABLE [ERP].[MovimientoTransferenciaMasivaCuenta] (
    [ID]                              INT             IDENTITY (1, 1) NOT NULL,
    [IdCuentaEmisor]                  INT             NOT NULL,
    [IdCategoriaTipoMovimientoEmisor] INT             NOT NULL,
    [IdMovimientoTesoreriaEmisor]     INT             NULL,
    [IdTalonarioEmisor]               INT             NULL,
    [NumeroChequeEmisor]              INT             NULL,
    [FechaEmisor]                     DATETIME        NULL,
    [FechaVencimientoEmisor]          DATETIME        NULL,
    [TipoCambioEmisor]                DECIMAL (14, 5) NULL,
    [MontoEmisor]                     DECIMAL (14, 5) NULL,
    [AjusteEmisor]                    DECIMAL (14, 5) NULL,
    [DocumentoEmisor]                 VARCHAR (25)    NULL,
    [ObservacionEmisor]               VARCHAR (MAX)   NULL,
    [OrdenDeEmisor]                   VARCHAR (MAX)   NULL,
    [FlagChequeDiferido]              BIT             NULL,
    [FlagCheque]                      BIT             NULL,
    [FechaRegistro]                   DATETIME        NULL,
    [UsuarioRegistro]                 VARCHAR (250)   NULL,
    [FechaModificado]                 DATETIME        NULL,
    [UsuarioModifico]                 VARCHAR (250)   NULL,
    [IdEmpresa]                       INT             NULL,
    [Flag]                            BIT             NULL,
    [FlagBorrador]                    BIT             NULL,
    [Orden]                           INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IdCategoriaTipoMovimientoEmisor]) REFERENCES [Maestro].[CategoriaTipoMovimiento] ([ID]),
    FOREIGN KEY ([IdCuentaEmisor]) REFERENCES [ERP].[Cuenta] ([ID]),
    FOREIGN KEY ([IdMovimientoTesoreriaEmisor]) REFERENCES [ERP].[MovimientoTesoreria] ([ID])
);

