CREATE TABLE [ERP].[MovimientoTesoreria] (
    [ID]                        INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]                 INT             NULL,
    [IdPeriodo]                 INT             NULL,
    [IdCuenta]                  INT             NULL,
    [IdTipoMovimiento]          INT             NULL,
    [Fecha]                     DATETIME        NULL,
    [FechaVencimiento]          DATETIME        NULL,
    [TipoCambio]                DECIMAL (14, 5) NULL,
    [Voucher]                   VARCHAR (25)    NULL,
    [NumeroCheque]              INT             NULL,
    [Nombre]                    VARCHAR (250)   NULL,
    [Observacion]               VARCHAR (250)   NULL,
    [IdEntidad]                 INT             NULL,
    [IdTalonario]               INT             NULL,
    [Total]                     DECIMAL (14, 5) NULL,
    [Flag]                      BIT             NULL,
    [FlagBorrador]              BIT             NULL,
    [FechaModificado]           DATETIME        NULL,
    [UsuarioRegistro]           VARCHAR (250)   NULL,
    [UsuarioModifico]           VARCHAR (250)   NULL,
    [UsuarioElimino]            VARCHAR (250)   NULL,
    [UsuarioActivo]             VARCHAR (250)   NULL,
    [FechaActivacion]           DATETIME        NULL,
    [FechaRegistro]             DATETIME        NULL,
    [Orden]                     INT             NULL,
    [IdCategoriaTipoMovimiento] INT             NULL,
    [FechaEliminado]            DATETIME        NULL,
    [FlagTransferencia]         BIT             NULL,
    [FlagCajaChica]             BIT             NULL,
    [FlagRindioCuenta]          BIT             NULL,
    [FlagConciliado]            BIT             NULL,
    [IdMovimientoConciliacion]  INT             NULL,
    [IdAsiento]                 INT             NULL,
    [IdMoneda]                  INT             NULL,
    [FlagCheque]                BIT             NULL,
    [FlagChequeDiferido]        BIT             NULL,
    CONSTRAINT [PK__Movimien__3214EC272C12E434] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Movimient__IdCue__20238DFD] FOREIGN KEY ([IdCuenta]) REFERENCES [ERP].[Cuenta] ([ID]),
    CONSTRAINT [FK__Movimient__IdEmp__1E3B458B] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK__Movimient__IdEnt__220BD66F] FOREIGN KEY ([IdEntidad]) REFERENCES [ERP].[Entidad] ([ID]),
    CONSTRAINT [FK__Movimient__IdTal__22FFFAA8] FOREIGN KEY ([IdTalonario]) REFERENCES [ERP].[Talonario] ([ID]),
    CONSTRAINT [FK__Movimient__IdTip__2117B236] FOREIGN KEY ([IdTipoMovimiento]) REFERENCES [Maestro].[TipoMovimiento] ([ID])
);

