CREATE TABLE [ERP].[OrdenServicio] (
    [ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [IdMoneda]              INT             NULL,
    [IdProveedor]           INT             NULL,
    [IdProyecto]            INT             NULL,
    [IdOrdenServicioEstado] INT             NULL,
    [Fecha]                 DATETIME        NULL,
    [TipoCambio]            DECIMAL (14, 5) NULL,
    [IdTipoComprobante]     INT             NULL,
    [Serie]                 VARCHAR (4)     NULL,
    [Documento]             VARCHAR (8)     NULL,
    [DiasVencimiento]       INT             NULL,
    [FechaVencimiento]      DATETIME        NULL,
    [Observacion]           VARCHAR (MAX)   NULL,
    [UsuarioRegistro]       VARCHAR (250)   NULL,
    [FechaRegistro]         DATETIME        NULL,
    [UsuarioModifico]       VARCHAR (250)   NULL,
    [FechaModificado]       DATETIME        NULL,
    [UsuarioActivo]         VARCHAR (250)   NULL,
    [FechaActivacion]       DATETIME        NULL,
    [UsuarioElimino]        VARCHAR (250)   NULL,
    [FechaEliminado]        DATETIME        NULL,
    [Flag]                  BIT             NULL,
    [FlagBorrador]          BIT             NULL,
    [ObservacionRechazado]  VARCHAR (MAX)   NULL,
    [IdEmpresa]             INT             NULL,
    [SubTotal]              DECIMAL (14, 5) NULL,
    [IGV]                   DECIMAL (14, 5) NULL,
    [Total]                 DECIMAL (14, 5) NULL,
    [PorcentajeIGV]         DECIMAL (14, 5) NULL,
    [Contacto]              VARCHAR (255)   NULL,
    [FormaPago]             VARCHAR (255)   NULL,
    [TiempoServicio]        VARCHAR (255)   NULL,
    [Direccion]             VARCHAR (255)   NULL,
    CONSTRAINT [PK__OrdenSer__3214EC2740787E1A] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__OrdenServ__IdMon__5853A3DE] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK__OrdenServ__IdOrd__5D1858FB] FOREIGN KEY ([IdOrdenServicioEstado]) REFERENCES [Maestro].[OrdenServicioEstado] ([ID]),
    CONSTRAINT [FK__OrdenServ__IdPro__5947C817] FOREIGN KEY ([IdProveedor]) REFERENCES [ERP].[Proveedor] ([ID]),
    CONSTRAINT [FK__OrdenServ__IdPro__5A3BEC50] FOREIGN KEY ([IdProyecto]) REFERENCES [ERP].[Proyecto] ([ID])
);

