CREATE TABLE [ERP].[OrdenCompra] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [IdMoneda]             INT             NULL,
    [IdProveedor]          INT             NULL,
    [IdProyecto]           INT             NULL,
    [IdEstablecimiento]    INT             NULL,
    [IdAlmacen]            INT             NULL,
    [IdOrdenCompraEstado]  INT             NULL,
    [Fecha]                DATETIME        NULL,
    [TipoCambio]           DECIMAL (14, 5) NULL,
    [IdTipoComprobante]    INT             NULL,
    [Serie]                VARCHAR (4)     NULL,
    [Documento]            VARCHAR (8)     NULL,
    [DiasVencimiento]      INT             NULL,
    [FechaVencimiento]     DATETIME        NULL,
    [Observacion]          VARCHAR (MAX)   NULL,
    [UsuarioRegistro]      VARCHAR (250)   NULL,
    [FechaRegistro]        DATETIME        NULL,
    [UsuarioModifico]      VARCHAR (250)   NULL,
    [FechaModificado]      DATETIME        NULL,
    [UsuarioActivo]        VARCHAR (250)   NULL,
    [FechaActivacion]      DATETIME        NULL,
    [UsuarioElimino]       VARCHAR (250)   NULL,
    [FechaEliminado]       DATETIME        NULL,
    [Flag]                 BIT             NULL,
    [FlagBorrador]         BIT             NULL,
    [ObservacionRechazado] VARCHAR (MAX)   NULL,
    [IdEmpresa]            INT             NULL,
    [SubTotal]             DECIMAL (14, 5) NULL,
    [IGV]                  DECIMAL (14, 5) NULL,
    [Total]                DECIMAL (14, 5) NULL,
    [PorcentajeIGV]        DECIMAL (14, 5) NULL,
    [FlagComparador]       BIT             NULL,
    [CondicionPago]        VARCHAR (250)   NULL,
    CONSTRAINT [PK__OrdenCom__3214EC2740787E1A] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__OrdenComp__IdAlm__5C2434C2] FOREIGN KEY ([IdAlmacen]) REFERENCES [ERP].[Almacen] ([ID]),
    CONSTRAINT [FK__OrdenComp__IdEst__5B301089] FOREIGN KEY ([IdEstablecimiento]) REFERENCES [ERP].[Establecimiento] ([ID]),
    CONSTRAINT [FK__OrdenComp__IdMon__5853A3DE] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK__OrdenComp__IdOrd__5D1858FB] FOREIGN KEY ([IdOrdenCompraEstado]) REFERENCES [Maestro].[OrdenCompraEstado] ([ID]),
    CONSTRAINT [FK__OrdenComp__IdPro__5947C817] FOREIGN KEY ([IdProveedor]) REFERENCES [ERP].[Proveedor] ([ID]),
    CONSTRAINT [FK__OrdenComp__IdPro__5A3BEC50] FOREIGN KEY ([IdProyecto]) REFERENCES [ERP].[Proyecto] ([ID])
);

