CREATE TABLE [ERP].[PedidoDetalle] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [IdPedido]                  INT             NOT NULL,
    [IdProducto]                INT             NOT NULL,
    [Nombre]                    VARCHAR (MAX)   NULL,
    [Cantidad]                  DECIMAL (14, 5) NULL,
    [PorcentajeDescuento]       DECIMAL (14, 5) NULL,
    [PorcentajeISC]             DECIMAL (14, 5) NULL,
    [PrecioPromedio]            DECIMAL (14, 5) NULL,
    [PrecioUnitarioLista]       DECIMAL (14, 5) NULL,
    [PrecioUnitarioListaSinIGV] DECIMAL (14, 5) NULL,
    [PrecioUnitarioValorISC]    DECIMAL (14, 5) NULL,
    [PrecioUnitarioISC]         DECIMAL (14, 5) NULL,
    [PrecioUnitarioDescuento]   DECIMAL (14, 5) NULL,
    [PrecioUnitarioSubTotal]    DECIMAL (14, 5) NULL,
    [PrecioUnitarioIGV]         DECIMAL (14, 5) NULL,
    [PrecioUnitarioTotal]       DECIMAL (14, 5) NULL,
    [PrecioLista]               DECIMAL (14, 5) NULL,
    [PrecioDescuento]           DECIMAL (14, 5) NULL,
    [PrecioSubTotal]            DECIMAL (14, 5) NULL,
    [PrecioIGV]                 DECIMAL (14, 5) NULL,
    [PrecioTotal]               DECIMAL (14, 5) NULL,
    [FechaRegistro]             DATETIME        NULL,
    [FechaEliminado]            DATETIME        NULL,
    [FlagBorrador]              BIT             NULL,
    [Flag]                      BIT             NULL,
    [FlagAfecto]                BIT             NULL,
    [FlagISC]                   BIT             NULL,
    [FlagOtrosImpuesto]         BIT             NULL,
    [FlagGratuito]              BIT             NULL,
    [FechaModificado]           DATETIME        NULL,
    [UsuarioRegistro]           VARCHAR (250)   NULL,
    [UsuarioModifico]           VARCHAR (250)   NULL,
    [UsuarioElimino]            VARCHAR (250)   NULL,
    [UsuarioActivo]             VARCHAR (250)   NULL,
    [FechaActivacion]           DATETIME        NULL,
    [NumeroLote]                VARCHAR (20)    NULL,
    [Fecha]                     DATETIME        NULL,
    FOREIGN KEY ([IdPedido]) REFERENCES [ERP].[Pedido] ([ID]),
    CONSTRAINT [FK__PedidoDet__IdPro__683FF2E4] FOREIGN KEY ([IdProducto]) REFERENCES [ERP].[Producto] ([ID])
);

