CREATE TABLE [ERP].[Pedido] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]                INT             NOT NULL,
    [IdTipoComprobante]        INT             NOT NULL,
    [IdCliente]                INT             NULL,
    [IdProyecto]               INT             NULL,
    [IdVendedor]               INT             NULL,
    [IdAlmacen]                INT             NULL,
    [IdMoneda]                 INT             NULL,
    [IdListaPrecio]            INT             NULL,
    [IdEstablecimiento]        INT             NULL,
    [IdDetraccion]             INT             NULL,
    [Serie]                    CHAR (4)        NULL,
    [Documento]                VARCHAR (20)    NULL,
    [SerieDocumento]           VARCHAR (20)    NULL,
    [Fecha]                    DATETIME        NULL,
    [DiasVencimiento]          INT             NULL,
    [FechaVencimiento]         DATETIME        NULL,
    [Observacion]              VARCHAR (250)   NULL,
    [TipoCambio]               DECIMAL (14, 5) NULL,
    [PorcentajeIGV]            DECIMAL (14, 5) NULL,
    [PorcentajeDescuento]      DECIMAL (14, 5) NULL,
    [PorcentajePercepcion]     DECIMAL (14, 5) NULL,
    [PorcentajeDetraccion]     DECIMAL (14, 5) NULL,
    [TotalDetalleISC]          DECIMAL (14, 5) NULL,
    [TotalDetalleAfecto]       DECIMAL (14, 5) NULL,
    [TotalDetalleInafecto]     DECIMAL (14, 5) NULL,
    [TotalDetalleExportacion]  DECIMAL (14, 5) NULL,
    [TotalDetalleGratuito]     DECIMAL (14, 5) NULL,
    [TotalDetalle]             DECIMAL (14, 5) NULL,
    [ImporteDetraccion]        DECIMAL (14, 5) NULL,
    [TotalDetraccion]          DECIMAL (14, 5) NULL,
    [ImporteDescuento]         DECIMAL (14, 5) NULL,
    [SubTotal]                 DECIMAL (14, 5) NULL,
    [IGV]                      DECIMAL (14, 5) NULL,
    [Total]                    DECIMAL (14, 5) NULL,
    [ISC]                      DECIMAL (14, 5) NULL,
    [ImportePercepcion]        DECIMAL (14, 5) NULL,
    [TotalPercepcion]          DECIMAL (14, 5) NULL,
    [FlagExportacion]          BIT             NULL,
    [FlagPercepcion]           BIT             NULL,
    [FlagDetraccion]           BIT             NULL,
    [FlagAnticipo]             BIT             NULL,
    [FlagBorrador]             BIT             NULL,
    [Flag]                     BIT             NULL,
    [UsuarioRegistro]          VARCHAR (250)   NULL,
    [FechaRegistro]            DATETIME        NULL,
    [FechaModificado]          DATETIME        NULL,
    [UsuarioModifico]          VARCHAR (250)   NULL,
    [FechaAnulado]             DATETIME        NULL,
    [UsuarioAnulo]             VARCHAR (250)   NULL,
    [IdPedidoEstado]           INT             NULL,
    [EstablecimientoDestino]   VARCHAR (250)   NULL,
    [IdEstablecimientoCliente] INT             NULL,
    CONSTRAINT [PK_Pedido] PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IdAlmacen]) REFERENCES [ERP].[Almacen] ([ID]),
    FOREIGN KEY ([IdCliente]) REFERENCES [ERP].[Cliente] ([ID]),
    FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    FOREIGN KEY ([IdListaPrecio]) REFERENCES [ERP].[ListaPrecio] ([ID]),
    FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    FOREIGN KEY ([IdProyecto]) REFERENCES [ERP].[Proyecto] ([ID]),
    FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID]),
    FOREIGN KEY ([IdVendedor]) REFERENCES [ERP].[Vendedor] ([ID]),
    CONSTRAINT [FK__Pedido__IdEstabl__609ED11C] FOREIGN KEY ([IdEstablecimiento]) REFERENCES [ERP].[Establecimiento] ([ID])
);

