CREATE TABLE [ERP].[PlanCuenta] (
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]        INT           NULL,
    [IdAnio]           INT           NULL,
    [CuentaContable]   VARCHAR (20)  NULL,
    [Nombre]           VARCHAR (250) NULL,
    [IdGrado]          INT           NULL,
    [IdColumnaBalance] INT           NULL,
    [IdMoneda]         INT           NULL,
    [IdTipoCambio]     INT           NULL,
    [EstadoAnalisis]   BIT           NULL,
    [EstadoProyecto]   BIT           NULL,
    [FlagBorrador]     BIT           NULL,
    [Flag]             BIT           NULL,
    [FechaEliminado]   DATETIME      NULL,
    [FechaRegistro]    DATETIME      NULL,
    [FechaModificado]  DATETIME      NULL,
    [UsuarioRegistro]  VARCHAR (250) NULL,
    [UsuarioModifico]  VARCHAR (250) NULL,
    [UsuarioElimino]   VARCHAR (250) NULL,
    [UsuarioActivo]    VARCHAR (250) NULL,
    [FechaActivacion]  DATETIME      NULL,
    CONSTRAINT [PK_PlanCuenta] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__PlanCuent__IdAni__70547F4A] FOREIGN KEY ([IdAnio]) REFERENCES [Maestro].[Anio] ([ID]),
    CONSTRAINT [FK_PlanCuenta_ColumnaBalance] FOREIGN KEY ([IdColumnaBalance]) REFERENCES [Maestro].[ColumnaBalance] ([ID]),
    CONSTRAINT [FK_PlanCuenta_Empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK_PlanCuenta_Grado] FOREIGN KEY ([IdGrado]) REFERENCES [Maestro].[Grado] ([ID]),
    CONSTRAINT [FK_PlanCuenta_Moneda] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK_PlanCuenta_TipoCambio] FOREIGN KEY ([IdTipoCambio]) REFERENCES [Maestro].[TipoCambio] ([ID])
);

