CREATE TABLE [ERP].[Proyecto] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]           INT             NULL,
    [Nombre]              VARCHAR (250)   NULL,
    [Numero]              VARCHAR (10)    NULL,
    [FechaInicio]         DATETIME        NULL,
    [FechaFin]            DATETIME        NULL,
    [FechaRegistro]       DATETIME        NULL,
    [FechaEliminado]      DATETIME        NULL,
    [FlagCierre]          BIT             NULL,
    [FlagBorrador]        BIT             NULL,
    [Flag]                BIT             NULL,
    [FechaModificado]     DATETIME        NULL,
    [UsuarioRegistro]     VARCHAR (250)   NULL,
    [UsuarioModifico]     VARCHAR (250)   NULL,
    [UsuarioElimino]      VARCHAR (250)   NULL,
    [UsuarioActivo]       VARCHAR (250)   NULL,
    [FechaActivacion]     DATETIME        NULL,
    [IdCliente]           INT             NULL,
    [PresupuestoVenta]    DECIMAL (14, 5) NULL,
    [PresupuestoCompra]   DECIMAL (14, 5) NULL,
    [IdMoneda]            INT             NULL,
    [IdTipoProyecto]      INT             NULL,
    [IdProyectoPrincipal] INT             NULL,
    [IgvVenta]            DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_IgvVenta] DEFAULT ((0)) NOT NULL,
    [TotalVenta]          DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_TotalVenta] DEFAULT ((0)) NOT NULL,
    [IgvCompra]           DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_IgvCompra] DEFAULT ((0)) NOT NULL,
    [TotalCompra]         DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_TotalCompra] DEFAULT ((0)) NOT NULL,
    [Utilidad]            DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_Utilidad] DEFAULT ((0)) NOT NULL,
    [IgvUtilidad]         DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_IgvUtilidad] DEFAULT ((0)) NOT NULL,
    [TotalUtilidad]       DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_TotalUtilidad] DEFAULT ((0)) NOT NULL,
    [PorcentajeUtilidad]  DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_PorcentajeUtilidad] DEFAULT ((0)) NOT NULL,
    [Igv]                 DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_Igv] DEFAULT ((0)) NOT NULL,
    [FechaCierre]         DATETIME        NULL,
    [PresupuestoCompraM]  DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_PresupuestoCompraM] DEFAULT ((0)) NOT NULL,
    [IgvCompraM]          DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_IgvCompraM] DEFAULT ((0)) NOT NULL,
    [TotalCompraM]        DECIMAL (14, 5) CONSTRAINT [DF_Proyecto_TotalCompraM] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__Proyecto__3214EC27714C96AE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Proyecto__IdEmpr__4301EA8F] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK_Proyecto_Cliente] FOREIGN KEY ([IdCliente]) REFERENCES [ERP].[Cliente] ([ID]),
    CONSTRAINT [FK_Proyecto_IdMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID])
);

