CREATE TABLE [ERP].[Requerimiento] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [Fecha]                 DATETIME      NULL,
    [IdTipoComprobante]     INT           NULL,
    [Serie]                 CHAR (4)      NULL,
    [Documento]             VARCHAR (8)   NULL,
    [IdEntidad]             INT           NULL,
    [DiasVencimiento]       INT           NULL,
    [FechaVencimiento]      DATETIME      NULL,
    [IdEstablecimiento]     INT           NULL,
    [IdProyecto]            INT           NULL,
    [FechaRegistro]         DATETIME      NULL,
    [UsuarioRegistro]       VARCHAR (250) NULL,
    [FechaModificado]       DATETIME      NULL,
    [UsuarioModifico]       VARCHAR (250) NULL,
    [FechaEliminado]        DATETIME      NULL,
    [UsuarioElimino]        VARCHAR (250) NULL,
    [FechaActivacion]       DATETIME      NULL,
    [UsuarioActivo]         VARCHAR (250) NULL,
    [FlagBorrador]          BIT           NULL,
    [Flag]                  BIT           NULL,
    [IdEmpresa]             INT           NULL,
    [IdRequerimientoEstado] INT           NULL,
    [Observacion]           VARCHAR (MAX) NULL,
    [ObservacionRechazado]  VARCHAR (MAX) NULL,
    CONSTRAINT [PK__Requerim__3214EC27D2A46200] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Requerimi__IdEnt__391002AF] FOREIGN KEY ([IdEntidad]) REFERENCES [ERP].[Entidad] ([ID]),
    CONSTRAINT [FK__Requerimi__IdEst__3A0426E8] FOREIGN KEY ([IdEstablecimiento]) REFERENCES [ERP].[Establecimiento] ([ID]),
    CONSTRAINT [FK__Requerimi__IdPro__3AF84B21] FOREIGN KEY ([IdProyecto]) REFERENCES [ERP].[Proyecto] ([ID]),
    CONSTRAINT [FK_Requerimiento_Estado] FOREIGN KEY ([IdRequerimientoEstado]) REFERENCES [Maestro].[RequerimientoEstado] ([ID])
);

