CREATE TABLE [ERP].[SaldoInicialCobrar] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [IdCliente]         INT             NULL,
    [IdTipoComprobante] INT             NULL,
    [Fecha]             DATETIME        NULL,
    [FechaVencimiento]  DATETIME        NULL,
    [Serie]             VARCHAR (4)     NULL,
    [Documento]         VARCHAR (8)     NULL,
    [Monto]             DECIMAL (14, 5) NULL,
    [Flag]              BIT             NULL,
    [FlagBorrador]      BIT             NULL,
    [IdEmpresa]         INT             NULL,
    [TipoCambio]        DECIMAL (14, 5) NULL,
    [IdMoneda]          INT             NULL,
    [FechaRegistro]     DATETIME        NULL,
    [FechaActivacion]   DATETIME        NULL,
    [FechaEliminado]    DATETIME        NULL,
    [FechaModificado]   DATETIME        NULL,
    [UsuarioRegistro]   VARCHAR (250)   NULL,
    [UsuarioModifico]   VARCHAR (250)   NULL,
    [UsuarioActivo]     VARCHAR (250)   NULL,
    [UsuarioElimino]    VARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IdCliente]) REFERENCES [ERP].[Cliente] ([ID]),
    FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID])
);

