CREATE TABLE [ERP].[TipoComprobantePlanCuenta] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]         INT           NULL,
    [IdTipoComprobante] INT           NULL,
    [IdTipoRelacion]    INT           NULL,
    [IdMoneda]          INT           NULL,
    [IdPlanCuenta]      INT           NULL,
    [IdSistema]         INT           NULL,
    [Nombre]            VARCHAR (250) NULL,
    [Abreviatura]       VARCHAR (50)  NULL,
    [FechaRegistro]     DATETIME      NULL,
    [FechaEliminado]    DATETIME      NULL,
    [FlagBorrador]      BIT           NULL,
    [Flag]              BIT           NULL,
    [FechaModificado]   DATETIME      NULL,
    [UsuarioRegistro]   VARCHAR (250) NULL,
    [UsuarioModifico]   VARCHAR (250) NULL,
    [UsuarioElimino]    VARCHAR (250) NULL,
    [UsuarioActivo]     VARCHAR (250) NULL,
    [FechaActivacion]   DATETIME      NULL,
    [IdAnio]            INT           NULL,
    CONSTRAINT [PK_TipoComprobantePlanCuenta] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_Empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_Moneda] FOREIGN KEY ([IdMoneda]) REFERENCES [Maestro].[Moneda] ([ID]),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_PlanCuenta] FOREIGN KEY ([IdPlanCuenta]) REFERENCES [ERP].[PlanCuenta] ([ID]),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_Sistema] FOREIGN KEY ([IdSistema]) REFERENCES [Seguridad].[Sistema] ([ID]),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_T10TipoComprobante] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [PLE].[T10TipoComprobante] ([ID]),
    CONSTRAINT [FK_TipoComprobantePlanCuenta_TipoRelacion] FOREIGN KEY ([IdTipoRelacion]) REFERENCES [Maestro].[TipoRelacion] ([ID])
);

