CREATE TABLE [ERP].[Transformacion] (
    [ID]                     INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]              INT             NULL,
    [IdTransformacionEstado] INT             NULL,
    [IdAlmacenOrigen]        INT             NULL,
    [IdAlmacenDestino]       INT             NULL,
    [IdMoneda]               INT             NULL,
    [IdProyecto]             INT             NULL,
    [Observaciones]          VARCHAR (250)   NULL,
    [Fecha]                  DATETIME        NULL,
    [FechaIngreso]           DATETIME        NULL,
    [FechaSalida]            DATETIME        NULL,
    [IdValeIngreso]          INT             NULL,
    [IdValeSalida]           INT             NULL,
    [Documento]              VARCHAR (8)     NULL,
    [UsuarioRegistro]        VARCHAR (250)   NULL,
    [FechaRegistro]          DATETIME        NULL,
    [UsuarioModifico]        VARCHAR (250)   NULL,
    [FechaModificado]        DATETIME        NULL,
    [UsuarioActivo]          VARCHAR (250)   NULL,
    [FechaActivacion]        DATETIME        NULL,
    [UsuarioElimino]         VARCHAR (250)   NULL,
    [FechaEliminado]         DATETIME        NULL,
    [FlagBorrador]           BIT             NULL,
    [Flag]                   BIT             NULL,
    [PorcentajeIGV]          DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_Transformacion] PRIMARY KEY CLUSTERED ([ID] ASC)
);

