CREATE TABLE [ERP].[Vacacion] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [IdDatoLaboral]       INT             NULL,
    [IdEmpresa]           INT             NULL,
    [IdPeriodo]           INT             NULL,
    [FechaInicio]         DATETIME        NULL,
    [FechaFin]            DATETIME        NULL,
    [Corresponde]         VARCHAR (10)    NULL,
    [HNormal]             DECIMAL (14, 5) NULL,
    [SueldoMinimo]        DECIMAL (14, 5) NULL,
    [PorcentajeAFamiliar] DECIMAL (14, 5) NULL,
    [AFamiliar]           DECIMAL (14, 5) NULL,
    [HE25]                DECIMAL (14, 5) NULL,
    [HE35]                DECIMAL (14, 5) NULL,
    [HE100]               DECIMAL (14, 5) NULL,
    [Bonificacion]        DECIMAL (14, 5) NULL,
    [Comision]            DECIMAL (14, 5) NULL,
    [Promedio]            DECIMAL (14, 5) NULL,
    [ValorDia]            DECIMAL (14, 5) NULL,
    [Dias]                DECIMAL (14, 5) NULL,
    [Total]               DECIMAL (14, 5) NULL,
    [Flag]                BIT             NULL,
    [UsuarioRegistro]     VARCHAR (250)   NULL,
    [FechaRegistro]       DATETIME        NULL,
    [UsuarioModifico]     VARCHAR (250)   NULL,
    [FechaModificado]     DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IdDatoLaboral]) REFERENCES [ERP].[DatoLaboral] ([ID]),
    FOREIGN KEY ([IdEmpresa]) REFERENCES [ERP].[Empresa] ([ID]),
    FOREIGN KEY ([IdPeriodo]) REFERENCES [ERP].[Periodo] ([ID])
);

