CREATE TABLE [ERP].[Vale] (
    [ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]          INT             NULL,
    [IdTipoMovimiento]   INT             NOT NULL,
    [IdEntidad]          INT             NULL,
    [IdConcepto]         INT             NULL,
    [IdProyecto]         INT             NULL,
    [IdAlmacen]          INT             NULL,
    [IdMoneda]           INT             NULL,
    [IdValeEstado]       INT             NULL,
    [Orden]              INT             NULL,
    [IdTipoComprobante]  INT             NULL,
    [Serie]              VARCHAR (4)     NULL,
    [Documento]          VARCHAR (8)     NULL,
    [Fecha]              DATETIME        NULL,
    [TipoCambio]         DECIMAL (14, 5) NULL,
    [PorcentajeIGV]      DECIMAL (14, 5) NULL,
    [SubTotal]           DECIMAL (14, 5) NULL,
    [IGV]                DECIMAL (14, 5) NULL,
    [Total]              DECIMAL (14, 5) NULL,
    [Peso]               DECIMAL (14, 5) NULL,
    [Observacion]        VARCHAR (250)   NULL,
    [FlagTransferencia]  BIT             NULL,
    [FlagTransformacion] BIT             NULL,
    [FlagBorrador]       BIT             NULL,
    [Flag]               BIT             NULL,
    [UsuarioRegistro]    VARCHAR (250)   NULL,
    [FechaRegistro]      DATETIME        NULL,
    [UsuarioModifico]    VARCHAR (250)   NULL,
    [FechaModificado]    DATETIME        NULL,
    [UsuarioElimino]     VARCHAR (250)   NULL,
    [FechaEliminado]     DATETIME        NULL,
    [UsuarioActivo]      VARCHAR (250)   NULL,
    [FechaActivacion]    DATETIME        NULL,
    [FlagComprobante]    BIT             NULL,
    [FlagGuiaRemision]   BIT             NULL,
    [FlagImportacion]    BIT             NULL,
    CONSTRAINT [PK_Vale] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Vale_Estado] FOREIGN KEY ([IdValeEstado]) REFERENCES [Maestro].[ValeEstado] ([ID]),
    CONSTRAINT [fk_vale_tipomovimiento] FOREIGN KEY ([IdTipoMovimiento]) REFERENCES [Maestro].[TipoMovimiento] ([ID])
);

