CREATE TABLE [dbo].[PLANGENERALDECUENTAS$] (
    [CUENTA]       FLOAT (53)     NULL,
    [DESCRIPCION]  NVARCHAR (255) NULL,
    [TIP]          NVARCHAR (255) NULL,
    [NIV]          FLOAT (53)     NULL,
    [ANE]          NVARCHAR (255) NULL,
    [ANE REF]      NVARCHAR (255) NULL,
    [CEN COS]      NVARCHAR (255) NULL,
    [DOC REF]      NVARCHAR (255) NULL,
    [FEC]          NVARCHAR (255) NULL,
    [ARE]          NVARCHAR (255) NULL,
    [F11]          NVARCHAR (255) NULL,
    [REG]          NVARCHAR (255) NULL,
    [MON]          NVARCHAR (255) NULL,
    [CON]          NVARCHAR (255) NULL,
    [CUENTA CARGO] NVARCHAR (255) NULL,
    [CUENTA ABONO] NVARCHAR (255) NULL,
    [BAL#]         FLOAT (53)     NULL,
    [GYP-LI]       NVARCHAR (255) NULL,
    [COS#]         NVARCHAR (255) NULL,
    [LARGO]        FLOAT (53)     NULL,
    [GRADO]        FLOAT (53)     NULL,
    [Moneda]       NVARCHAR (255) NULL,
    [TIPO CAMBIO]  NVARCHAR (255) NULL,
    [BALANCE]      NVARCHAR (255) NULL,
    [ANALISIS]     NVARCHAR (255) NULL,
    [PROYECTO]     NVARCHAR (255) NULL,
    [IdMoneda]     FLOAT (53)     NULL
);

